### ISSUE TITLE
High cpu usage and freeze

### ISSUE THREAD

**Issue by MrNinja008** [JonyGamesYT9/AntiFrameEdit#1]
Ok so i have added a item that cant be placeable in itemframe from Config.. and after i uploaded this plugin my server started freezing often and high cpu usage so i checked timings and it shows your plugin let me show you pic. I cant ss the timings so i will attach the lonk
https://timings.pmmp.io/?id=158503
![IMG_20210828_161215](https://user-images.githubusercontent.com/79526396/131215391-e0b5b2fe-a740-4563-b08e-66ca3bf066d4.jpg)

**Comment by MrNinja008** [comment]
Pls optimize your plugin

**Comment by JonyGamesYT9** [comment]
Ya esta echo. ;)

**Comment by JonyGamesYT9** [comment]
I just rewrote the plugin, I hope and I no longer have problems of exaggerated CPU usage :)
